### PR TITLE
fix: fix various regression on latest refactor

### LINKED ISSUE #106: `svm install <version>` and `svm list` failures
The following functions from the README fail:

> -   List available versions
> 
> ```sh
> svm list
> ```
> 
> -   Install a version
> 
> ```sh
> svm install <version>
> ```

image

Installation was from source via `cargo install --locked --git https://github.com/roynalnaruto/svm-rs`

### PR DESCRIPTION
**Pull request by mattsse**
fixes a bunch of stuff overlooked in 

https://github.com/alloy-rs/svm-rs/pull/102

closes #106

usage regression: use unnamed args again
incorrect usage of block_on

### CODE REVIEW

**Review by Evalir — APPROVED** [review]
😅

File: crates/svm-rs/src/bin/svm-bin/usev.rs [hunk 1]
```diff
@@ -5,7 +5,7 @@ use semver::Version;
 
 #[derive(Debug, Clone, Parser)]
 pub struct UseArgs {
-    #[clap(long, short)]
+    #[clap(help = "Solc version to use")]
```
Comment (DaniPopes) [inline crates/svm-rs/src/bin/svm-bin/usev.rs:8]: help -> doccomment

**Review by DaniPopes — CHANGES_REQUESTED** [review]
